### PR TITLE
Datastore detail arguments and persistence unit name logic improvement

### PR DESCRIPTION
**Pull request by dtsw**
Fix for #5

### CODE REVIEW

**Comment by andyjefferson** [comment]
Thanks for the contrib. While this may meet your immediate needs it (if I understand it correctly) doesn't make total sense (to me). 

My expectations, based on your requirement
1. If the user has specified the datastore details on the SchemaTool popup page then use those ALWAYS.
2. If not 1, but datastore details were specified in SchemaTool Preferences then use those.
3. If not 1 and 2, and the persistence-unit name is specified, then use that.

So if it followed that order of priority, you could simply define your persistence unit name in Preferences and specify nothing else. Make sense?

**Comment by dtsw** [comment]
yes, this makes sense. But with the current code, the plugin uses the Datastore Details from Preferences even when they are empty. The -pu is also added to the arguments, but the  SchemaTool fails because of the empty Datastore Details.
With my contrib, if a Persistence Unit is specified in Preferences, the Datastore Details are ignored and the Schema Tool will pick all the settings from the persistence.xml.
Actually, a Persistence Unit name textfield on the popup would make the Plugin more consistent.

**Comment by andyjefferson** [comment]
Yes I know, so if you change your code to reflect what priority I said above then the PR can be accepted ...
i.e if the "connectionURL" is specified (not null and not whitespace) then use the datastore details, otherwise if the "persistenceUnit" is specified then use that, ... and if none of those then just throw an error.

**Comment by dtsw** [comment]
I have modified line 160 to check connectionURL. I think this covers all 3 cases above.

**Pull request merged**
